### ISSUE TITLE
Move this repository to the `jenkinsci` GitHub organization

### ISSUE THREAD

**Issue by basil** [jenkinsci/file-leak-detector#55]
As part of my work on the Java 11 upgrade in Jenkins, I am planning to refresh this library and add Java 11 support.

Refreshing this library would be easiest for me to do if it lived in the `jenkinsci` GitHub organization. If moved, I plan to:

- Update the parent POM to the latest Jenkins parent POM
- Merge one of the open Java 11 PRs
- Publish a release to the Jenkins project Artifactory server
- Update [CloudBees File Leak Detector](https://plugins.jenkins.io/file-leak-detector/) to use the new release

Consensus regarding this plan was reached in [this mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/PXnJe2G8xJc/m/jy90M2m9AwAJ).

CC @kohsuke @timja

**Comment by centic9** [comment]
I would love to have this repo being re-animated. 

I have some more changes on various branches on https://github.com/centic9/file-leak-detector, some of them are good candidates for being upstreamed into the main repo.

**Comment by basil** [comment]
@kohsuke Gentle ping.

**Comment by kohsuke** [comment]
OK, sounds good. Another project graduating from my nest.

**Comment by kohsuke** [comment]
Transferred!

**Comment by basil** [comment]
Thank you!
